# Generated by Django 4.1.3 on 2022-11-14 18:55

import apps.helpers
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("contact", models.CharField(max_length=50, unique=True)),
                (
                    "photo",
                    models.ImageField(
                        default="", upload_to=apps.helpers.save_company_image
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                ("website", models.URLField(unique=True)),
                ("location", models.TextField()),
            ],
        ),
    ]
