# Generated by Django 4.1.3 on 2022-11-14 18:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("creation_date", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("creation_date", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("sum_assurance", models.PositiveIntegerField()),
                ("premium", models.PositiveIntegerField()),
                ("tenure", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PolicyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("creation_date", models.DateField(auto_now=True)),
                ("status", models.CharField(default="Pending", max_length=100)),
                ("date_created", models.DateField(default=django.utils.timezone.now)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_records",
                        to="insurances.policy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
