# Generated by Django 4.1.3 on 2022-11-14 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("insurances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policyrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policy_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policies",
                to="insurances.category",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policies",
                to="companies.company",
            ),
        ),
    ]
